const data = [
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_1",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "16027",
    followersCount: "1754183",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_2",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "12290",
    followersCount: "1587811",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
  {
    _id: "dummy_id_3",
    domain: "swiggy.com",
    __v: 0,
    employeeCount: "15000",
    followersCount: "1800000",
    linkedinProfile: "https://in.linkedin.com/company/swiggy-in",
  },
  {
    _id: "dummy_id_4",
    domain: "zomato.com",
    __v: 0,
    employeeCount: "13000",
    followersCount: "1650000",
    linkedinProfile: "https://in.linkedin.com/company/zomato",
  },
];

export default data;
